# -*- coding: utf-8 -*-
"""task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tr-6DZgCDTbPtWdTEiaP6bMKbPlh5p26
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#import dataset
df = pd.read_csv("/content/drive/MyDrive/Elevate Labs/Titanic-Dataset.csv")

#Check dataset structure
df.isnull().sum()

#Handle missing values
#Missing values are age, cabin, and embarked
df["Age"] = df["Age"].fillna(df["Age"].median())

#Cabin and Embarked are types object
df[["Cabin", "Embarked"]] = df[["Cabin", "Embarked"]].fillna("Unknown")

#Describe numerical features in dataset
# print(df.info())
df.describe()

# Describe full dataset
print("\nFull Summary (including categorical):\n", df.describe(include='all'))

# Median separately (since describe() doesn't show it explicitly sometimes)
print("\nMedian Values:\n", df.median(numeric_only=True))

# Standard deviation
print("\nStandard Deviation:\n", df.std(numeric_only=True))

df.columns

"""Graphs"""

#Histogram

df["Fare"].hist(figsize=(12, 8), bins=20)
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Passengers")
plt.show()

#Another histogram for fare distribution of every passengers

plt.figure(figsize=(12, 8))
sns.histplot(df["Fare"], bins=20, kde=True)

plt.title("Fare Distribution with Density Curve")
plt.xlabel("Fare")
plt.ylabel("Passengers")
plt.show()

#Age Distribution
df['Age'].hist(figsize=(12, 8), bins=20)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Passengers")
plt.show()

#Boxplot for passenger's age
plt.figure(figsize=(12, 6))
plt.title("Age Outliers")
sns.boxplot(x='Pclass', y='Age', data=df[['Pclass', 'Age']])

#Outliers for Fare
plt.figure(figsize=(12, 6))
plt.title("Fare Outliers")
sns.boxplot(x='Pclass', y='Fare', data=df[['Pclass', 'Fare']])

#Pairplot showing the relationship between features
sns.pairplot(df[["Age", "SibSp", "Fare", "Survived"]])
plt.show()

#Interpretation
# The data is skewed (especially Fare)
# Most passengers traveled alone
# There are clear outliers

#Correlation Matrix
plt.figure(figsize=(10, 8))
correlation_matrix = df[["Age", "Fare", "SibSp", "Survived", "Pclass", "Parch"]].corr()

sns.heatmap(correlation_matrix,
            annot=True,
            cmap='coolwarm',
            fmt=".2f")

plt.title("Correlation Matrix")
plt.show()

"""Identify Patterns, Trends, and Anomalies"""

numeric_cols = ["Age", "Fare", "Survived", "Parch", "SibSp"]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col} - Number of Outliers: {outliers.shape[0]}")

#Check skewness
print("\nSkewness:\n", df[numeric_cols].skew())

"""Feature-Level Inference"""

#Does Survived depend on Age and Sex?
plt.figure(figsize=(10,5))
sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survived")
plt.show()

#Visualize survived vs sex
plt.figure(figsize=(6,5))
sns.countplot(x='Survived', hue='Sex', data=df, palette=['skyblue','salmon'])
plt.title("Survived by Sex")
plt.show()

# Does Fare affect Pclass?
plt.figure(figsize=(10,5))
sns.boxplot(x='Pclass', y='Fare', data=df)
plt.title("Fare by Pclass")
plt.show()

# Does Pclass affect the survival rate?
plt.figure(figsize=(8,5))
sns.countplot(x='Pclass', hue='Survived', data=df, palette=['salmon','skyblue'])
plt.title("Survival Count by Pclass")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")
plt.legend(title="Survived", labels=["No (0)", "Yes (1)"])
plt.show()